# Generated by Django 5.0.4 on 2024-05-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
    ]
