# Generated by Django 5.0.4 on 2024-05-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='name',
            field=models.CharField(default=True, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='index',
            name='email',
            field=models.ImageField(max_length=120, upload_to=''),
        ),
    ]
