# Generated by Django 5.0.4 on 2024-05-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_index_name_alter_index_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Index',
        ),
    ]
