# Generated by Django 5.0.4 on 2024-05-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_car_delete_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
