# Generated by Django 5.0.4 on 2024-05-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_car_id_alter_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='car',
            name='surname',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
