# Generated by Django 5.0.4 on 2024-05-28 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('food', models.CharField(default=True, max_length=120)),
                ('drink', models.CharField(default=True, max_length=120)),
                ('sos1', models.CharField(default=False, max_length=120)),
                ('sos2', models.CharField(default=False, max_length=120)),
                ('desc', models.TextField(default=True)),
                ('adet', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sweet', models.BooleanField(null=True)),
                ('ice', models.BooleanField(null=True)),
                ('snack', models.BooleanField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('addres', models.CharField(max_length=120)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='users',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.restaurant'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
