# Generated by Django 5.0.4 on 2024-05-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_order_restaurant_remove_car_users_delete_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sweet',
        ),
    ]
