# Generated by Django 5.0.4 on 2024-05-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_order_ice_remove_order_sweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=True, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=True, max_length=15),
            preserve_default=False,
        ),
    ]
