# Generated by Django 5.0.4 on 2024-05-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_order_address_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=25)),
                ('delivery', models.ManyToManyField(to='project.restaurant')),
            ],
        ),
    ]
